LA0151FA.XYW



' *********** BIRTHDAY.BAS **************

100 CLS
110 Person$ = "Vickie"
120 Birthday$ = "06-12-1989"
130 IF Birthday$ <> DATE$ THEN SYSTEM
140 PRINT TAB(5); "Happy birthday to you . . ."
150 PLAY "o3 c8 c8 d c f e2"
160 PRINT TAB(10); "Happy birthday to you . . ."
170 PLAY "c8 c8 d c g f2"
180 PRINT TAB(15); "Happy birthday dear "; Person$; " . . ."
190 PLAY "c8 c8 o4 c o3 a f e d2"
200 PRINT TAB(20); "Happy birthday to YOU!!"
210 PLAY "t90 b-8 b-8 a f g f2"




®BB¯®PT7¯®AL0¯®LM0¯®RM67¯®LS2¯®MDBO¯Figure A:®MDNM¯ When this little BASIC program is run it will play "Happy Birthday." Place it in someone's autoexec file on that person's birthday.
